dist: trusty
language: cpp
compiler:
        - clang
        - gcc
addons:
        apt:
                packages:
                        - libboost-test-dev
script:
        - ./autogen.sh
        - make
        - make check